### PR TITLE
Support for large datasets

### PR DESCRIPTION
**Pull request by joannecheng**
## What does this PR do? How does it affect users?

This adds support for rendering large datasets.

Major changes:
* Adds `.paginate` method to public API, `.visibilityThreshold` option to `chartOptions`.
* Adds a new demo page (`test/demo/pagination.html`) to play around with these new features.
* `render` function in `libraries/default.js`: If the new dataviz methods (`paginate` or `visibilityThreshold`) are set to true, `render` will call new extension functions to render charts. These extension functions live in `libraries/c3_extensions/`

### Line Charts and Bar Charts

This allows for large datasets to be rendered in chunks, which improves the performance of the page by reducing the number of SVG elements with mouse event handlers on the page, prevents charts from breaking, and provides a cleaner user interface.

linegraph

### Stacked Bar and Area Charts

If `stacked` is `true` and `paginate` is `true and there more than 15 data points, stacked bar and area graphs render an 'Other' bar.
 
screen shot 2016-02-17 at 3 06 39 pm

### Pie and Donut Charts

A `visibilityThreshold` option is available for users. If the user sets it, it'll throw all data points with a fractional value less than that threshold into an "Other" slice. Setting this option will reduce the chance we'll render a pie with so many slices that it slows down the page and becomes unreadable. This feature is based off of a feature on google charts:

piegraphs

## How should this be tested?

Run `gulp` and go to `demo/index.html`. Look at the "Paginated Line Graph" example and navigate around.

Then go to `demo/pagination.html`. Change the `visibilityThreshold` attribute for the pie/donut charts, and make sure every data point under the visibility threshold you set goes into the 'Other' slice. Play around with the `paginate` function as well.

Fetch the branch and/or deploy to staging to test the following:

- [ ] Does the code compile without warnings (check shell, console)?
- [ ] Do all tests pass?
- [ ] Does the UI, pixel by pixel, look exactly as expected (check various screen sizes, including mobile)?
- [ ] If the feature makes requests from the browser, inspect them in the Web Inspector. Do they look as expected (parameters, headers, etc)?
- [ ] If the feature sends data to Keen, is the data visible in the project if you run an extraction (include link to collection/query)?
- [ ] If the feature saves data to a database, can you confirm the data is indeed created in the database?

### CODE REVIEW

**Comment by dustinlarimer** [comment]
Excellent work, this thing kicks ass :boom: Works great with legend positioning and sorting too, since it loads post-render. 

screen shot 2016-02-04 at 1 04 57 pm

**Q:** How would you like to approach stacked datasets, like for area/bar charts? Omitting records will detract from the whole, so perhaps in `stacked = true` we could roll up the omitted values into an "Other" series?

**Comment by joannecheng** [comment]
@dustinlarimer throwing everything into an `other` category is a really good idea, I hadn't thought of that. Planning to do that with donut/pie charts too. Far from impossible to do.

**Comment by joannecheng** [comment]
@dustinlarimer I'm working on getting pagination for other charts, but in another branch. Should I continue to put all the changes in this branch?

**Comment by dustinlarimer** [comment]
Sure, let's keep it all here.

**Comment by dustinlarimer** [comment]
This is looking pretty sharp!

I think I found a corner case where pagination doesn't take effect if `summarize` is `true`, but I'm not sure where/how that might be happening.. could there be a leaky condition somewhere?

**Comment by joannecheng** [comment]
@dustinlarimer Thanks for taking a look and the kind words!

I purposely turned off `pagination` if `summarize`is set to true https://github.com/keen/keen-dataviz.js/pull/14/files#diff-9a21b3b699ef60b8d22d4a46ae8a1c49R1615

The reason is that "summarizing" a stacked bar or stacked area would give the same effect as `paginating`, and I would want `summarize` to take priority... but a user could try to set both `summarize` and `pagination` to true on a non-stacked graph and see no changes to the graph. Going to see if there's a better way to write that logic.

**Comment by dustinlarimer** [comment]
Encountered an error with this set on the demo page:

```javascript
chart
  .type('bar')
  .summarize(true)
  .paginate(false)
  .render();
```

> **keen-dataviz.js:1380** 
> Uncaught TypeError: Cannot read property 'concat' of undefined(…)
> summarizeChart @ keen-dataviz.js:1380
> types.(anonymous function).render @ keen-dataviz.js:1552
> (anonymous function) @ keen-dataviz.js:1103
> domReady @ keen-dataviz.js:1221
> Dataviz.render @ keen-dataviz.js:1092
> (anonymous function) @ VM5348:2
> InjectedScript._evaluateOn @ VM5082:875
> InjectedScript._evaluateAndWrap @ VM5082:808
> InjectedScript.evaluate @ VM5082:664

**Comment by dustinlarimer** [comment]
Awesome, great update.. looks like it's working as expected now!

Couple of quick Qs:

Is there anything going on internally that might be causing these labels to overlap?
screen shot 2016-02-23 at 3 03 44 pm

Also, can we control the load-order for summarized data, so that "Other (Generated)" is shows up last in the legend?

**Comment by dustinlarimer** [comment]
Last commit resolves #22.

**Comment by dustinlarimer** [comment]
Possibly an error w/ the 'Other' label? 

screen shot 2016-02-26 at 12 54 44 pm


Repro:
```javascript
Keen.Dataviz.find('.chart-c3-line-with-pagination')
  .type('bar')
  .stacked(true)
  .render();
```

**Comment by joannecheng** [comment]
This was already merged in with https://github.com/keen/keen-dataviz.js/pull/37

**Pull request closed without merging**
