### PR TITLE
Release 1.0.3

### PR DESCRIPTION
**Pull request by aroc**
## What does this PR?
It makes the necessary changes to release `v1.0.3`.

### CODE REVIEW

**Comment by dustinlarimer** [comment]
Looks good - just need to update the URLs here as well: https://github.com/keen/keen-dataviz.js/blob/master/docs/README.md

**Comment by aroc** [comment]
@dustinlarimer Are they not already updated? 
image

**Comment by dustinlarimer** [comment]
There's a readme in the docs folder too.

**Comment by aroc** [comment]
Ahhh. I misread that URL. Ok updated.

**Pull request merged**
